/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * Screen4Hire - AI-powered recruitment platform for multi-corporation use
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get current employer profile
 */
export declare const GetMyProfileResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clerkUserId: zod.ZodString;
    companyName: zod.ZodString;
    email: zod.ZodString;
    industry: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}>;
/**
 * @summary Create employer profile on first login
 */
export declare const CreateMyProfileBody: zod.ZodObject<{
    companyName: zod.ZodString;
    email: zod.ZodString;
    industry: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    companyName: string;
    email: string;
    industry?: string | undefined;
}, {
    companyName: string;
    email: string;
    industry?: string | undefined;
}>;
export declare const CreateMyProfileResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clerkUserId: zod.ZodString;
    companyName: zod.ZodString;
    email: zod.ZodString;
    industry: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}>;
/**
 * @summary Update employer profile
 */
export declare const UpdateMyProfileBody: zod.ZodObject<{
    companyName: zod.ZodOptional<zod.ZodString>;
    industry: zod.ZodOptional<zod.ZodString>;
    logoUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    companyName?: string | undefined;
    industry?: string | undefined;
    logoUrl?: string | undefined;
}, {
    companyName?: string | undefined;
    industry?: string | undefined;
    logoUrl?: string | undefined;
}>;
export declare const UpdateMyProfileResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clerkUserId: zod.ZodString;
    companyName: zod.ZodString;
    email: zod.ZodString;
    industry: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}, {
    id: number;
    clerkUserId: string;
    companyName: string;
    email: string;
    createdAt: string;
    industry?: string | null | undefined;
    logoUrl?: string | null | undefined;
}>;
/**
 * @summary Employer dashboard with pipeline overview
 */
export declare const GetDashboardResponse: zod.ZodObject<{
    totalJobs: zod.ZodNumber;
    activeJobs: zod.ZodNumber;
    totalApplications: zod.ZodNumber;
    pendingScreening: zod.ZodNumber;
    questionnairesSent: zod.ZodNumber;
    finalistsSelected: zod.ZodNumber;
    interviewsCompleted: zod.ZodNumber;
    recentActivity: zod.ZodArray<zod.ZodObject<{
        type: zod.ZodString;
        description: zod.ZodString;
        timestamp: zod.ZodString;
        jobTitle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        description: string;
        timestamp: string;
        jobTitle?: string | null | undefined;
    }, {
        type: string;
        description: string;
        timestamp: string;
        jobTitle?: string | null | undefined;
    }>, "many">;
    jobsSummary: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        status: zod.ZodString;
        applications: zod.ZodNumber;
        finalists: zod.ZodNumber;
        interviewed: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        title: string;
        applications: number;
        finalists: number;
        interviewed: number;
    }, {
        status: string;
        id: number;
        title: string;
        applications: number;
        finalists: number;
        interviewed: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalJobs: number;
    activeJobs: number;
    totalApplications: number;
    pendingScreening: number;
    questionnairesSent: number;
    finalistsSelected: number;
    interviewsCompleted: number;
    recentActivity: {
        type: string;
        description: string;
        timestamp: string;
        jobTitle?: string | null | undefined;
    }[];
    jobsSummary: {
        status: string;
        id: number;
        title: string;
        applications: number;
        finalists: number;
        interviewed: number;
    }[];
}, {
    totalJobs: number;
    activeJobs: number;
    totalApplications: number;
    pendingScreening: number;
    questionnairesSent: number;
    finalistsSelected: number;
    interviewsCompleted: number;
    recentActivity: {
        type: string;
        description: string;
        timestamp: string;
        jobTitle?: string | null | undefined;
    }[];
    jobsSummary: {
        status: string;
        id: number;
        title: string;
        applications: number;
        finalists: number;
        interviewed: number;
    }[];
}>;
/**
 * @summary List all jobs for the current employer
 */
export declare const ListJobsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    employerId: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodEnum<["draft", "active", "closed"]>;
    applicationCount: zod.ZodNumber;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}>;
export declare const ListJobsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    employerId: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodEnum<["draft", "active", "closed"]>;
    applicationCount: zod.ZodNumber;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new job posting
 */
export declare const createJobBodyMaxCandidatesToEmailMax = 100;
export declare const CreateJobBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodString>;
    location: zod.ZodOptional<zod.ZodString>;
    salaryRange: zod.ZodOptional<zod.ZodString>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodOptional<zod.ZodEnum<["draft", "active"]>>;
}, "strip", zod.ZodTypeAny, {
    description: string;
    title: string;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    status?: "draft" | "active" | undefined;
    department?: string | undefined;
    location?: string | undefined;
    salaryRange?: string | undefined;
}, {
    description: string;
    title: string;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    status?: "draft" | "active" | undefined;
    department?: string | undefined;
    location?: string | undefined;
    salaryRange?: string | undefined;
}>;
export declare const CreateJobResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    employerId: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodEnum<["draft", "active", "closed"]>;
    applicationCount: zod.ZodNumber;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}>;
/**
 * @summary Get a job posting
 */
export declare const GetJobParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetJobResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    employerId: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodEnum<["draft", "active", "closed"]>;
    applicationCount: zod.ZodNumber;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}>;
/**
 * @summary Update a job posting
 */
export declare const UpdateJobParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateJobBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    department: zod.ZodOptional<zod.ZodString>;
    location: zod.ZodOptional<zod.ZodString>;
    salaryRange: zod.ZodOptional<zod.ZodString>;
    screeningCriteria: zod.ZodOptional<zod.ZodString>;
    maxCandidatesToEmail: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodEnum<["draft", "active", "closed"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "draft" | "active" | "closed" | undefined;
    description?: string | undefined;
    title?: string | undefined;
    department?: string | undefined;
    location?: string | undefined;
    salaryRange?: string | undefined;
    screeningCriteria?: string | undefined;
    maxCandidatesToEmail?: number | undefined;
}, {
    status?: "draft" | "active" | "closed" | undefined;
    description?: string | undefined;
    title?: string | undefined;
    department?: string | undefined;
    location?: string | undefined;
    salaryRange?: string | undefined;
    screeningCriteria?: string | undefined;
    maxCandidatesToEmail?: number | undefined;
}>;
export declare const UpdateJobResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    employerId: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    screeningCriteria: zod.ZodString;
    maxCandidatesToEmail: zod.ZodNumber;
    status: zod.ZodEnum<["draft", "active", "closed"]>;
    applicationCount: zod.ZodNumber;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}, {
    status: "draft" | "active" | "closed";
    id: number;
    createdAt: string;
    description: string;
    title: string;
    employerId: number;
    screeningCriteria: string;
    maxCandidatesToEmail: number;
    applicationCount: number;
    updatedAt: string;
    department?: string | null | undefined;
    location?: string | null | undefined;
    salaryRange?: string | null | undefined;
}>;
/**
 * @summary Delete a job posting
 */
export declare const DeleteJobParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteJobResponse: zod.ZodVoid;
/**
 * @summary Get pipeline statistics for a job
 */
export declare const GetJobStatsParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetJobStatsResponse: zod.ZodObject<{
    jobId: zod.ZodNumber;
    totalApplications: zod.ZodNumber;
    screened: zod.ZodNumber;
    questionnairesSent: zod.ZodNumber;
    responsesReceived: zod.ZodNumber;
    finalistsSelected: zod.ZodNumber;
    interviewsScheduled: zod.ZodNumber;
    interviewsCompleted: zod.ZodNumber;
    averageAiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    totalApplications: number;
    questionnairesSent: number;
    finalistsSelected: number;
    interviewsCompleted: number;
    jobId: number;
    screened: number;
    responsesReceived: number;
    interviewsScheduled: number;
    averageAiScore?: number | null | undefined;
}, {
    totalApplications: number;
    questionnairesSent: number;
    finalistsSelected: number;
    interviewsCompleted: number;
    jobId: number;
    screened: number;
    responsesReceived: number;
    interviewsScheduled: number;
    averageAiScore?: number | null | undefined;
}>;
/**
 * @summary List all applications for a job
 */
export declare const ListApplicationsParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const ListApplicationsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>;
export declare const ListApplicationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>, "many">;
/**
 * @summary Submit a new application (resume as text or base64 PDF)
 */
export declare const CreateApplicationParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const CreateApplicationBody: zod.ZodObject<{
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodString>;
    resumeText: zod.ZodOptional<zod.ZodString>;
    resumeBase64: zod.ZodOptional<zod.ZodString>;
    resumeFileName: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    email: string;
    candidateName: string;
    phone?: string | undefined;
    resumeFileName?: string | undefined;
    resumeText?: string | undefined;
    resumeBase64?: string | undefined;
}, {
    email: string;
    candidateName: string;
    phone?: string | undefined;
    resumeFileName?: string | undefined;
    resumeText?: string | undefined;
    resumeBase64?: string | undefined;
}>;
export declare const CreateApplicationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>;
/**
 * @summary Get a single application with full details
 */
export declare const GetApplicationParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetApplicationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeText: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiStrengths: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiWeaknesses: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodString;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    job: zod.ZodObject<{
        id: zod.ZodNumber;
        employerId: zod.ZodNumber;
        title: zod.ZodString;
        description: zod.ZodString;
        department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        salaryRange: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        screeningCriteria: zod.ZodString;
        maxCandidatesToEmail: zod.ZodNumber;
        status: zod.ZodEnum<["draft", "active", "closed"]>;
        applicationCount: zod.ZodNumber;
        createdAt: zod.ZodString;
        updatedAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "draft" | "active" | "closed";
        id: number;
        createdAt: string;
        description: string;
        title: string;
        employerId: number;
        screeningCriteria: string;
        maxCandidatesToEmail: number;
        applicationCount: number;
        updatedAt: string;
        department?: string | null | undefined;
        location?: string | null | undefined;
        salaryRange?: string | null | undefined;
    }, {
        status: "draft" | "active" | "closed";
        id: number;
        createdAt: string;
        description: string;
        title: string;
        employerId: number;
        screeningCriteria: string;
        maxCandidatesToEmail: number;
        applicationCount: number;
        updatedAt: string;
        department?: string | null | undefined;
        location?: string | null | undefined;
        salaryRange?: string | null | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    job: {
        status: "draft" | "active" | "closed";
        id: number;
        createdAt: string;
        description: string;
        title: string;
        employerId: number;
        screeningCriteria: string;
        maxCandidatesToEmail: number;
        applicationCount: number;
        updatedAt: string;
        department?: string | null | undefined;
        location?: string | null | undefined;
        salaryRange?: string | null | undefined;
    };
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
    resumeText?: string | null | undefined;
    aiStrengths?: string | null | undefined;
    aiWeaknesses?: string | null | undefined;
}, {
    status: string;
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    job: {
        status: "draft" | "active" | "closed";
        id: number;
        createdAt: string;
        description: string;
        title: string;
        employerId: number;
        screeningCriteria: string;
        maxCandidatesToEmail: number;
        applicationCount: number;
        updatedAt: string;
        department?: string | null | undefined;
        location?: string | null | undefined;
        salaryRange?: string | null | undefined;
    };
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
    resumeText?: string | null | undefined;
    aiStrengths?: string | null | undefined;
    aiWeaknesses?: string | null | undefined;
}>;
/**
 * @summary Update application status or notes
 */
export declare const UpdateApplicationParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateApplicationBody: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>>;
    employerNotes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected" | undefined;
    employerNotes?: string | undefined;
}, {
    status?: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected" | undefined;
    employerNotes?: string | undefined;
}>;
export declare const UpdateApplicationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>;
/**
 * @summary Delete an application
 */
export declare const DeleteApplicationParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteApplicationResponse: zod.ZodVoid;
/**
 * @summary Run AI screening on all applications for a job
 */
export declare const ScreenApplicationsParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const ScreenApplicationsResponse: zod.ZodObject<{
    screened: zod.ZodNumber;
    message: zod.ZodString;
    applications: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        jobId: zod.ZodNumber;
        candidateName: zod.ZodString;
        email: zod.ZodString;
        phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
        employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
        id: number;
        email: string;
        createdAt: string;
        jobId: number;
        candidateName: string;
        phone?: string | null | undefined;
        resumeFileName?: string | null | undefined;
        aiScore?: number | null | undefined;
        aiSummary?: string | null | undefined;
        employerNotes?: string | null | undefined;
    }, {
        status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
        id: number;
        email: string;
        createdAt: string;
        jobId: number;
        candidateName: string;
        phone?: string | null | undefined;
        resumeFileName?: string | null | undefined;
        aiScore?: number | null | undefined;
        aiSummary?: string | null | undefined;
        employerNotes?: string | null | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    message: string;
    applications: {
        status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
        id: number;
        email: string;
        createdAt: string;
        jobId: number;
        candidateName: string;
        phone?: string | null | undefined;
        resumeFileName?: string | null | undefined;
        aiScore?: number | null | undefined;
        aiSummary?: string | null | undefined;
        employerNotes?: string | null | undefined;
    }[];
    screened: number;
}, {
    message: string;
    applications: {
        status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
        id: number;
        email: string;
        createdAt: string;
        jobId: number;
        candidateName: string;
        phone?: string | null | undefined;
        resumeFileName?: string | null | undefined;
        aiScore?: number | null | undefined;
        aiSummary?: string | null | undefined;
        employerNotes?: string | null | undefined;
    }[];
    screened: number;
}>;
/**
 * @summary Send email questionnaires to top candidates selected by employer criteria
 */
export declare const SendQuestionnairesParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const SendQuestionnairesBody: zod.ZodObject<{
    count: zod.ZodNumber;
    questions: zod.ZodArray<zod.ZodString, "many">;
    deadline: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    count: number;
    questions: string[];
    deadline?: string | undefined;
}, {
    count: number;
    questions: string[];
    deadline?: string | undefined;
}>;
export declare const SendQuestionnairesResponse: zod.ZodObject<{
    sent: zod.ZodNumber;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    sent: number;
}, {
    message: string;
    sent: number;
}>;
/**
 * @summary AI selects 3-5 finalists based on questionnaire responses
 */
export declare const SelectFinalistsParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const SelectFinalistsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>;
export declare const SelectFinalistsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    candidateName: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    resumeFileName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    aiSummary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["new", "screening", "questionnaire_sent", "questionnaire_responded", "finalist", "interview_scheduled", "interview_completed", "hired", "rejected"]>;
    employerNotes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}, {
    status: "new" | "screening" | "questionnaire_sent" | "questionnaire_responded" | "finalist" | "interview_scheduled" | "interview_completed" | "hired" | "rejected";
    id: number;
    email: string;
    createdAt: string;
    jobId: number;
    candidateName: string;
    phone?: string | null | undefined;
    resumeFileName?: string | null | undefined;
    aiScore?: number | null | undefined;
    aiSummary?: string | null | undefined;
    employerNotes?: string | null | undefined;
}>, "many">;
/**
 * @summary Get questionnaire for a candidate (public, via token)
 */
export declare const GetQuestionnaireParams: zod.ZodObject<{
    token: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    token: string;
}, {
    token: string;
}>;
export declare const GetQuestionnaireResponse: zod.ZodObject<{
    token: zod.ZodString;
    candidateName: zod.ZodString;
    companyName: zod.ZodString;
    jobTitle: zod.ZodString;
    questions: zod.ZodArray<zod.ZodString, "many">;
    deadline: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    alreadySubmitted: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    companyName: string;
    jobTitle: string;
    candidateName: string;
    questions: string[];
    token: string;
    alreadySubmitted: boolean;
    deadline?: string | null | undefined;
}, {
    companyName: string;
    jobTitle: string;
    candidateName: string;
    questions: string[];
    token: string;
    alreadySubmitted: boolean;
    deadline?: string | null | undefined;
}>;
/**
 * @summary Candidate submits questionnaire responses
 */
export declare const SubmitQuestionnaireParams: zod.ZodObject<{
    token: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    token: string;
}, {
    token: string;
}>;
export declare const SubmitQuestionnaireBody: zod.ZodObject<{
    answers: zod.ZodArray<zod.ZodString, "many">;
}, "strip", zod.ZodTypeAny, {
    answers: string[];
}, {
    answers: string[];
}>;
export declare const SubmitQuestionnaireResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    success: boolean;
}, {
    message: string;
    success: boolean;
}>;
/**
 * @summary Get questionnaire and response for an application (employer view)
 */
export declare const GetApplicationQuestionnaireParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetApplicationQuestionnaireResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    applicationId: zod.ZodNumber;
    token: zod.ZodString;
    questions: zod.ZodArray<zod.ZodString, "many">;
    sentAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    deadline: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["pending", "sent", "responded", "expired"]>;
    response: zod.ZodOptional<zod.ZodNullable<zod.ZodObject<{
        answers: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
        aiScore: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        aiAnalysis: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        submittedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        aiScore?: number | null | undefined;
        answers?: string[] | undefined;
        aiAnalysis?: string | null | undefined;
        submittedAt?: string | null | undefined;
    }, {
        aiScore?: number | null | undefined;
        answers?: string[] | undefined;
        aiAnalysis?: string | null | undefined;
        submittedAt?: string | null | undefined;
    }>>>;
}, "strip", zod.ZodTypeAny, {
    status: "sent" | "pending" | "responded" | "expired";
    id: number;
    questions: string[];
    token: string;
    applicationId: number;
    deadline?: string | null | undefined;
    sentAt?: string | null | undefined;
    response?: {
        aiScore?: number | null | undefined;
        answers?: string[] | undefined;
        aiAnalysis?: string | null | undefined;
        submittedAt?: string | null | undefined;
    } | null | undefined;
}, {
    status: "sent" | "pending" | "responded" | "expired";
    id: number;
    questions: string[];
    token: string;
    applicationId: number;
    deadline?: string | null | undefined;
    sentAt?: string | null | undefined;
    response?: {
        aiScore?: number | null | undefined;
        answers?: string[] | undefined;
        aiAnalysis?: string | null | undefined;
        submittedAt?: string | null | undefined;
    } | null | undefined;
}>;
/**
 * @summary List configured interview questions for a job
 */
export declare const ListInterviewQuestionsParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const ListInterviewQuestionsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    questionText: zod.ZodString;
    orderIndex: zod.ZodNumber;
    responseScript: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}>;
export declare const ListInterviewQuestionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    questionText: zod.ZodString;
    orderIndex: zod.ZodNumber;
    responseScript: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}>, "many">;
/**
 * @summary Add an interview question
 */
export declare const CreateInterviewQuestionParams: zod.ZodObject<{
    jobId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    jobId: number;
}, {
    jobId: number;
}>;
export declare const CreateInterviewQuestionBody: zod.ZodObject<{
    questionText: zod.ZodString;
    orderIndex: zod.ZodNumber;
    responseScript: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    questionText: string;
    orderIndex: number;
    responseScript?: string | undefined;
}, {
    questionText: string;
    orderIndex: number;
    responseScript?: string | undefined;
}>;
export declare const CreateInterviewQuestionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    questionText: zod.ZodString;
    orderIndex: zod.ZodNumber;
    responseScript: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}>;
/**
 * @summary Update an interview question
 */
export declare const UpdateInterviewQuestionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateInterviewQuestionBody: zod.ZodObject<{
    questionText: zod.ZodOptional<zod.ZodString>;
    orderIndex: zod.ZodOptional<zod.ZodNumber>;
    responseScript: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    questionText?: string | undefined;
    orderIndex?: number | undefined;
    responseScript?: string | undefined;
}, {
    questionText?: string | undefined;
    orderIndex?: number | undefined;
    responseScript?: string | undefined;
}>;
export declare const UpdateInterviewQuestionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    jobId: zod.ZodNumber;
    questionText: zod.ZodString;
    orderIndex: zod.ZodNumber;
    responseScript: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}, {
    id: number;
    createdAt: string;
    jobId: number;
    questionText: string;
    orderIndex: number;
    responseScript?: string | null | undefined;
}>;
/**
 * @summary Delete an interview question
 */
export declare const DeleteInterviewQuestionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteInterviewQuestionResponse: zod.ZodVoid;
/**
 * @summary Get interview session for an application
 */
export declare const GetInterviewSessionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetInterviewSessionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    applicationId: zod.ZodNumber;
    heygenSessionId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["pending", "active", "completed", "failed"]>;
    transcript: zod.ZodOptional<zod.ZodNullable<zod.ZodArray<zod.ZodObject<{
        role: zod.ZodOptional<zod.ZodString>;
        content: zod.ZodOptional<zod.ZodString>;
        time: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }>, "many">>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    completedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}>;
/**
 * @summary Create (schedule) an interview session for a finalist
 */
export declare const CreateInterviewSessionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const CreateInterviewSessionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    applicationId: zod.ZodNumber;
    heygenSessionId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["pending", "active", "completed", "failed"]>;
    transcript: zod.ZodOptional<zod.ZodNullable<zod.ZodArray<zod.ZodObject<{
        role: zod.ZodOptional<zod.ZodString>;
        content: zod.ZodOptional<zod.ZodString>;
        time: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }>, "many">>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    completedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}>;
/**
 * @summary Start HeyGen streaming session and get access token
 */
export declare const StartInterviewSessionParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const StartInterviewSessionResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    token: zod.ZodString;
    realtimeEndpoint: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    token: string;
    sessionId: string;
    realtimeEndpoint: string;
}, {
    token: string;
    sessionId: string;
    realtimeEndpoint: string;
}>;
/**
 * @summary Save transcript and notes after interview completes
 */
export declare const SaveInterviewTranscriptParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const SaveInterviewTranscriptBody: zod.ZodObject<{
    transcript: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        role: zod.ZodOptional<zod.ZodString>;
        content: zod.ZodOptional<zod.ZodString>;
        time: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }>, "many">>;
    notes: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodEnum<["completed", "failed"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "completed" | "failed" | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | undefined;
    notes?: string | undefined;
}, {
    status?: "completed" | "failed" | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | undefined;
    notes?: string | undefined;
}>;
export declare const SaveInterviewTranscriptResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    applicationId: zod.ZodNumber;
    heygenSessionId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["pending", "active", "completed", "failed"]>;
    transcript: zod.ZodOptional<zod.ZodNullable<zod.ZodArray<zod.ZodObject<{
        role: zod.ZodOptional<zod.ZodString>;
        content: zod.ZodOptional<zod.ZodString>;
        time: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }, {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }>, "many">>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    completedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}, {
    status: "active" | "pending" | "completed" | "failed";
    id: number;
    createdAt: string;
    applicationId: number;
    heygenSessionId?: string | null | undefined;
    transcript?: {
        role?: string | undefined;
        content?: string | undefined;
        time?: string | undefined;
    }[] | null | undefined;
    notes?: string | null | undefined;
    completedAt?: string | null | undefined;
}>;
//# sourceMappingURL=api.d.ts.map