/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * Screen4Hire - AI-powered recruitment platform for multi-corporation use
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationStatus } from './applicationStatus';

export interface Application {
  id: number;
  jobId: number;
  candidateName: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  resumeFileName?: string | null;
  /** @nullable */
  aiScore?: number | null;
  /** @nullable */
  aiSummary?: string | null;
  status: ApplicationStatus;
  /** @nullable */
  employerNotes?: string | null;
  createdAt: string;
}
