/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * Screen4Hire - AI-powered recruitment platform for multi-corporation use
 * OpenAPI spec version: 0.1.0
 */
export interface ApplicationInput {
    /** @minLength 1 */
    candidateName: string;
    email: string;
    phone?: string;
    /** Plain text resume content */
    resumeText?: string;
    /** Base64-encoded PDF resume */
    resumeBase64?: string;
    resumeFileName?: string;
}
//# sourceMappingURL=applicationInput.d.ts.map