/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * Screen4Hire - AI-powered recruitment platform for multi-corporation use
 * OpenAPI spec version: 0.1.0
 */

export interface EmployerUpdate {
  /** @minLength 1 */
  companyName?: string;
  industry?: string;
  logoUrl?: string;
}
