/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * Screen4Hire - AI-powered recruitment platform for multi-corporation use
 * OpenAPI spec version: 0.1.0
 */

export interface Employer {
  id: number;
  clerkUserId: string;
  companyName: string;
  email: string;
  /** @nullable */
  industry?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  createdAt: string;
}
